### PR TITLE
🐛 Fix Hash Comparison

### LINKED ISSUE #12: 🐛 ProcessDefinition import is broken, due to bug with bcryptjs
#### Describe your issue

There is currently a bug within bcrypt, which causes `bcrypt.compare()` to always return true, not matter what you put in there.
This in turn breaks the import/update of the ProcessDefinitions.

#### Possible Solution

Since we already have both hashes in hand, we should just use string comparison.

We can consider moving back to that function, if bcrypt fixes that issue, but frankly, I don't see the need.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by ElRaptorus**
**Changes:**

Fix the hash comparison, by directly comparing both hashed strings instead of using bcrypt.compare.

**Issues:**

Closes #12 

PR: #13

## How can others test the changes?

- Import a process model
- Now edit that process model and import it under the same name
- Note that there are now two entries for that process model.

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

File: src/process_definition_repository.ts [hunk 1]
```diff
@@ -53,7 +53,8 @@ export class ProcessDefinitionRepository implements IProcessDefinitionRepository
         throw new ConflictError(`Process definition with the name '${name}' already exists!`);
       }
 
-      const hashesMatch = await bcrypt.compare(xml, existingDefinition.hash);
+      // NOTE: bcrypt.compare() is broken. It ALWAYS returns true, no matter what you throw at it.
+      const hashesMatch: boolean = processDefinitionHash === existingDefinition.hash;
```
Comment (cmg-dev) [inline src/process_definition_repository.ts]: 👍

Comment (cmg-dev) [reply src/process_definition_repository.ts]: What a hideous little fella. Thanks @robpal94  for the report.
